title: Simple Page
icon: 📝
preset: page
fields:
  headline:
    type: text
    help: If specified, it replaces the title on the page itself.
  text:
    type: textarea
    size: huge
    required: true
